<!DOCTYPE html>
<!--suppress HtmlUnknownAttribute -->
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <title> Lampdesk </title>
	<link rel="stylesheet" href="/static/css/style.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<#import "/blocks/header.ftlh" as header>
<@header.header />
<h4 style="margin-left:30px;">Главная</h4>
<hr>

</body>
</html>